-- SQLD 209p~211p
-- 이론 확인 문제


-- 12번. LEVEL문제
SELECT LEVEL, EMPNO, ENAME, MGR FROM EMP
START WITH JOB = 'SALESMAN'
CONNECT BY PRIOR EMPNO = MGR;

-- 13번.
SELECT D.DNAME, E.JOB, SUM(E.SAL),COUNT(E.EMPNO)
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
GROUP BY(D.DNAME, E.JOB);